// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Communcation_Request_FullMethodName = "/Communcation/Request"
)

// CommuncationClient is the client API for Communcation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommuncationClient interface {
	Request(ctx context.Context, in *CriticalData, opts ...grpc.CallOption) (*Accept, error)
}

type communcationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommuncationClient(cc grpc.ClientConnInterface) CommuncationClient {
	return &communcationClient{cc}
}

func (c *communcationClient) Request(ctx context.Context, in *CriticalData, opts ...grpc.CallOption) (*Accept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Accept)
	err := c.cc.Invoke(ctx, Communcation_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommuncationServer is the server API for Communcation service.
// All implementations must embed UnimplementedCommuncationServer
// for forward compatibility.
type CommuncationServer interface {
	Request(context.Context, *CriticalData) (*Accept, error)
	mustEmbedUnimplementedCommuncationServer()
}

// UnimplementedCommuncationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommuncationServer struct{}

func (UnimplementedCommuncationServer) Request(context.Context, *CriticalData) (*Accept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedCommuncationServer) mustEmbedUnimplementedCommuncationServer() {}
func (UnimplementedCommuncationServer) testEmbeddedByValue()                      {}

// UnsafeCommuncationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommuncationServer will
// result in compilation errors.
type UnsafeCommuncationServer interface {
	mustEmbedUnimplementedCommuncationServer()
}

func RegisterCommuncationServer(s grpc.ServiceRegistrar, srv CommuncationServer) {
	// If the following call pancis, it indicates UnimplementedCommuncationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Communcation_ServiceDesc, srv)
}

func _Communcation_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriticalData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommuncationServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communcation_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommuncationServer).Request(ctx, req.(*CriticalData))
	}
	return interceptor(ctx, in, info, handler)
}

// Communcation_ServiceDesc is the grpc.ServiceDesc for Communcation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communcation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Communcation",
	HandlerType: (*CommuncationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Communcation_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
